on:
  workflow_dispatch:
    inputs:
      message:
        description: "Test message"
        required: true
 
  repository_dispatch:
    types: [run-from-powerautomate]
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
  - name: Print message
    run: echo "${{ github.event.inputs.message || github.event.client_payload.message }}"
